name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'dir.zip'
          #path: '.'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: py_test_func_pm
          zip_file: dir.zip
    
      #- name: Run a multi-line script to install another staff we could have via requirements.txt or separately
        #run: |
         #python3 -m pip install --upgrade pip
         #pip3 install -r requirements.txt
